// Table des ressources : chemins du projet de design -> URLs servies.
// Générée par tools/unpack.py à partir de l'export du design.
export const RESOURCES = {
  "../../assets/alien.svg": "/assets/alien.svg",
  "../../assets/alien2.png": "/assets/alien2.png",
  "../../assets/icons/confirmation_number.svg": "/assets/icons/confirmation_number.svg",
  "../../assets/icons/directions.svg": "/assets/icons/directions.svg",
  "../../assets/icons/edit_note.svg": "/assets/icons/edit_note.svg",
  "../../assets/icons/event.svg": "/assets/icons/event.svg",
  "../../assets/icons/instagram-white.png": "/assets/icons/instagram-white.png",
  "../../assets/icons/pause-pink.svg": "/assets/icons/pause-pink.svg",
  "../../assets/icons/pause.svg": "/assets/icons/pause.svg",
  "../../assets/icons/play-pink.svg": "/assets/icons/play-pink.svg",
  "../../assets/icons/play.svg": "/assets/icons/play.svg",
  "../../assets/icons/volunteer_activism-pink.svg": "/assets/icons/volunteer_activism-pink.svg",
  "../../assets/icons/volunteer_activism.svg": "/assets/icons/volunteer_activism.svg",
  "../../assets/photos/prog-bluelaika.png": "/assets/photos/prog-bluelaika.png",
  "../../assets/photos/prog-djfantastik.png": "/assets/photos/prog-djfantastik.png",
  "../../assets/photos/prog-emma.png": "/assets/photos/prog-emma.png",
  "../../assets/photos/prog-icimodesta.png": "/assets/photos/prog-icimodesta.png",
  "../../assets/photos/prog-juneexactly.png": "/assets/photos/prog-juneexactly.png",
  "../../assets/photos/prog-makatiass.png": "/assets/photos/prog-makatiass.png",
  "../../assets/photos/prog-matahata.png": "/assets/photos/prog-matahata.png",
  "../../assets/photos/prog-mille.png": "/assets/photos/prog-mille.png",
  "../../assets/photos/prog-peakybinder.png": "/assets/photos/prog-peakybinder.png",
  "../../assets/photos/prog-petrole.png": "/assets/photos/prog-petrole.png",
  "../../assets/photos/prog-queerbaku.png": "/assets/photos/prog-queerbaku.png",
  "../../assets/photos/prog-ravie.png": "/assets/photos/prog-ravie.png",
  "../../assets/photos/prog-singleladies.png": "/assets/photos/prog-singleladies.png",
  "../../assets/photos/prog-thomas.png": "/assets/photos/prog-thomas.png",
  "../../assets/photos/qif-01.jpg": "/assets/photos/qif-01.jpg",
  "../../assets/photos/qif-02.jpg": "/assets/photos/qif-02.jpg",
  "../../assets/photos/qif-03.jpg": "/assets/photos/qif-03.jpg",
  "../../assets/photos/qif-04.jpg": "/assets/photos/qif-04.jpg",
  "../../assets/photos/qif-05.jpg": "/assets/photos/qif-05.jpg",
  "../../assets/photos/qif-06.jpg": "/assets/photos/qif-06.jpg",
  "../../assets/photos/qif-07.jpg": "/assets/photos/qif-07.jpg",
  "../../assets/photos/qif-08.jpg": "/assets/photos/qif-08.jpg",
  "../../assets/photos/qif-09.jpg": "/assets/photos/qif-09.jpg",
  "../../assets/photos/qif-10.jpg": "/assets/photos/qif-10.jpg",
  "../../assets/photos/qif-11.jpg": "/assets/photos/qif-11.jpg",
  "../../assets/photos/tech-matt.png": "/assets/photos/tech-matt.png",
  "../../assets/photos/tech-virginie.png": "/assets/photos/tech-virginie.png",
  "../../assets/qif-logo.svg": "/assets/qif-logo.svg",
  "../../assets/shapes/qifstar.svg": "/assets/shapes/qifstar.svg",
  "../../assets/soucoupe.png": "/assets/soucoupe.png",
  "./anouch-mtaj34bs-seil.png": "/assets/team/anouch-mtaj34bs-seil.png",
  "./elea-mtaj0heb-4vd8.png": "/assets/team/elea-mtaj0heb-4vd8.png",
  "./fleur-mtfx33mw-6hzi.png": "/assets/team/fleur-mtfx33mw-6hzi.png",
  "./frame-2609264-mtaj15y6-r7pt.png": "/assets/team/frame-2609264-mtaj15y6-r7pt.png",
  "./lucil-mtfx39ri-7rpy.png": "/assets/team/lucil-mtfx39ri-7rpy.png",
  "./mathi-mtaj2quy-ou48.png": "/assets/team/mathi-mtaj2quy-ou48.png"
};

export function RES(path) {
  return RESOURCES[path] || path;
}
